# experiments
full:
  global:
    seed: [0,100,250]
    proj_interval: [1, 25, 50, 100, 500]
    train_mb_size: [32]
    eval_mb_size: [1000]
    n_experiences: [10]
    train_epochs: [1]
    lr: [0.01, 0.03, 0.1, 0.3]
    momentum: [0.0]
    patterns_per_exp: [256]
    memory_strength: [0.5]
    output_dir: ['./new_results/full/']
    cuda: [1]

  plugins:
    gem: 
      memory_size: [200, 1280, 2560, 5120]
    igem:
      addons: [adaptive_lr, warm_start]
      pgd_iterations: [3, 5]
    agem:
      sample_size: [256, 1300]

  benchmarks:
    permuted-mnist: [mlp]
    cifar100: [resnet18]
    mmlu-cl: [gpt2]

debug:
  global:
    proj_interval: [1]
    seed: [0, 2, 5, 7, 11]
    train_mb_size: [32]
    eval_mb_size: [50]
    n_experiences: [3]
    train_epochs: [5]
    lr: [0.001]
    momentum: [0.9]
    patterns_per_exp: [200]
    memory_strength: [0.3]
    output_dir: ['./new_results/debug/']
    cuda: [1]
    memory_size: [150]

  
  plugins:
    gem:
      blank: [None]
    igem:
      addons: [adaptive_lr, warm_start]
      pgd_iterations: [3]
    agem:
      sample_size: [10]
    # naive:
    #   blank: [None]

  benchmarks:
    # permuted-mnist: [mlp]
    #cifar100: [resnet18]
    mmlu-cl: [gpt2]
    #trec-cl: [gpt2]

# trec-cl
# debug:
#   global:
#     proj_interval: [1]
#     # seed: [0, 2, 5, 7, 11]
#     seed: [0, 7]
#     train_mb_size: [16]
#     eval_mb_size: [50]
#     n_experiences: [6]
#     train_epochs: [1]
#     lr: [0.0005]
#     momentum: [1.0]
#     patterns_per_exp: [50]
#     memory_strength: [0.5]
#     output_dir: ['./new_results/debug/']
#     cuda: [0]
#     memory_size: [600]

  
#   plugins:
#     gem:
#       blank: [None]
#     igem:
#       addons: [adaptive_lr, warm_start]
#       pgd_iterations: [3]
#     agem:
#       sample_size: [10]

#   benchmarks:
#     trec-cl: [gpt2]
